server:

#  ip: http://127.0.0.1:8181
  ip: https://server.blog.zorange.online
  port: 8181
spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    120.26.79.238
#    localhost
    url: jdbc:mysql://120.26.79.238/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 421232
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: online.zorange.blogserver.entity


files:
    upload:
      article: /home/server/files/article/
      img: /home/server/files/img/

#files:
#  upload:
#    article: C:\Users\orange\Desktop\毕业设计选题\博客系统\files\article\
#    img: C:\Users\orange\Desktop\毕业设计选题\博客系统\files\img\
#
